### ISSUE TITLE
Minimal prototype for demo

### ISSUE THREAD

**Issue by Crevil** [racketometer/planning#1]
The requirements for a minimal prototype for testing the product on users.

## Blocking things
- [ ] Sensor delivery

## Features
- [ ] Communication with sensor with BLE
- [ ] Data analysis with data analysis algorithms offline

## Views
- [ ] Find devices
- [ ] Start session
- [ ] Download and analyse data from racket
- [ ] Present findings

**Comment by Crevil** [comment]
@Karnich Have some inputs to this? I'm thinking an absolute minimal solution. This means no back-end integrations etc. Just the core functionality.

**Comment by Crevil** [comment]
@mboesen @KaareMoss Er dette fornuftigt? Er der noget I tænker mangler eller er overflødigt?
Og hvordan ser det ud med leveringen af sensoren?

**Comment by mboesen** [comment]
Det ser fint ud. Jeg pinger lige Hansen (igen) for update for firmware og batteri.

**Comment by Karnich** [comment]
@Crevil Synes det ser meget fornuftigt ud. Kører vi bare videre med NativeScript eller hvad tænker du omkring det?

**Comment by mboesen** [comment]
Der er en smule som skal laves om, så input data bliver analyseret med et kartotek af forskellige typer slagsekvenser. Det kræver dog at det kartotek bliver lavet, hvilket kræver, at slagsekvenserne lige skal optages først. /ToDoSoon

**Comment by Crevil** [comment]
@mboesen Vil du oprette et issue på den opgave, så vi har den tracket. Det vil i øvrigt være en fordel hvis algoritmerne ikke blev skrevet i Python fremad rettet. (I know, this is shocking) 
Jeg har omskrevet den vi fik i sin tid til TypeScript, hvilket gør at den kan kører på telefoner/tablets offline.
Der er ikke anvendt nogle Python specifikke ting i algoritmen, så det burde ikke være det største bump at skulle over. Det kan du lige keepe in mind.

@Karnich Well, jeg havde egentligt tænkt at vi kunne lave denne MVP i react native for at teste det af? Kravene er ikke så forskellige fra det vi allerede har i NativeScript, så hvis React viser sig mere klodset end {N} så kan vi jo bare tage den op igen. Hvad tænker du om det?

**Comment by mboesen** [comment]
@Crevil Vi har faktisk optaget slagene til kartoteket, så der skal "bare" laves et script som henter filerne ind og analyserer korrelation mellem input slaget og slagene i kartoteket. 
Jeg skal godt nok lige lære TypeScript, hvis det skal skrives om. 
Hvordan opretter man et issue? I r noob til waffle.io.

**Comment by Crevil** [comment]
@mboesen Jeg kan se at du fandt ud af det med [#206 på thesis repoet](https://github.com/racketometer/thesis/issues/206). Kan du lukke det igen og oprette det i dette repo (`planning`). Du kan enten gøre det igennem GitHub her: https://github.com/racketometer/planning/issues eller på Waffle ved at vælge repoet i dropdownen når du opretter et nyt.
